project:
  type: website

website:
  title: "Martin Westgate"
  navbar:
    right:
      - text: Blog
        href: posts.qmd
      - text: Outputs
        menu:
        - text: Papers
          href: papers.qmd
        - text: Packages
          href: packages.qmd
        - text: Presentations
          href: presentations.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true



